// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { BarDB } from './bar-db';
import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { KeyDB } from './key-db'
import { SerieDB } from './serie-db'

@Injectable({
  providedIn: 'root'
})
export class BarService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  BarServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private barsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.barsUrl = origin + '/api/github.com/fullstack-lang/gongd3/go/v1/bars';
  }

  /** GET bars from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB[]> {
    return this.getBars(GONG__StackPath, frontRepo)
  }
  getBars(GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<BarDB[]>(this.barsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<BarDB[]>('getBars', []))
      );
  }

  /** GET bar by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB> {
    return this.getBar(id, GONG__StackPath, frontRepo)
  }
  getBar(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.barsUrl}/${id}`;
    return this.http.get<BarDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched bar id=${id}`)),
      catchError(this.handleError<BarDB>(`getBar id=${id}`))
    );
  }

  /** POST: add a new bar to the server */
  post(bardb: BarDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB> {
    return this.postBar(bardb, GONG__StackPath, frontRepo)
  }
  postBar(bardb: BarDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    if (bardb.X != undefined) {
      bardb.BarPointersEncoding.XID.Int64 = bardb.X.ID
      bardb.BarPointersEncoding.XID.Valid = true
    }
    bardb.X = undefined
    if (bardb.Y != undefined) {
      bardb.BarPointersEncoding.YID.Int64 = bardb.Y.ID
      bardb.BarPointersEncoding.YID.Valid = true
    }
    bardb.Y = undefined
    bardb.BarPointersEncoding.Set = []
    for (let _serie of bardb.Set) {
      bardb.BarPointersEncoding.Set.push(_serie.ID)
    }
    bardb.Set = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<BarDB>(this.barsUrl, bardb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        bardb.X = frontRepo.Keys.get(bardb.BarPointersEncoding.XID.Int64)
        bardb.Y = frontRepo.Keys.get(bardb.BarPointersEncoding.YID.Int64)
        bardb.Set = new Array<SerieDB>()
        for (let _id of bardb.BarPointersEncoding.Set) {
          let _serie = frontRepo.Series.get(_id)
          if (_serie != undefined) {
            bardb.Set.push(_serie!)
          }
        }
        // this.log(`posted bardb id=${bardb.ID}`)
      }),
      catchError(this.handleError<BarDB>('postBar'))
    );
  }

  /** DELETE: delete the bardb from the server */
  delete(bardb: BarDB | number, GONG__StackPath: string): Observable<BarDB> {
    return this.deleteBar(bardb, GONG__StackPath)
  }
  deleteBar(bardb: BarDB | number, GONG__StackPath: string): Observable<BarDB> {
    const id = typeof bardb === 'number' ? bardb : bardb.ID;
    const url = `${this.barsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<BarDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted bardb id=${id}`)),
      catchError(this.handleError<BarDB>('deleteBar'))
    );
  }

  /** PUT: update the bardb on the server */
  update(bardb: BarDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB> {
    return this.updateBar(bardb, GONG__StackPath, frontRepo)
  }
  updateBar(bardb: BarDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<BarDB> {
    const id = typeof bardb === 'number' ? bardb : bardb.ID;
    const url = `${this.barsUrl}/${id}`;

    // insertion point for reset of pointers (to avoid circular JSON)
    // and encoding of pointers
    if (bardb.X != undefined) {
      bardb.BarPointersEncoding.XID.Int64 = bardb.X.ID
      bardb.BarPointersEncoding.XID.Valid = true
    }
    bardb.X = undefined
    if (bardb.Y != undefined) {
      bardb.BarPointersEncoding.YID.Int64 = bardb.Y.ID
      bardb.BarPointersEncoding.YID.Valid = true
    }
    bardb.Y = undefined
    bardb.BarPointersEncoding.Set = []
    for (let _serie of bardb.Set) {
      bardb.BarPointersEncoding.Set.push(_serie.ID)
    }
    bardb.Set = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<BarDB>(url, bardb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        bardb.X = frontRepo.Keys.get(bardb.BarPointersEncoding.XID.Int64)
        bardb.Y = frontRepo.Keys.get(bardb.BarPointersEncoding.YID.Int64)
        bardb.Set = new Array<SerieDB>()
        for (let _id of bardb.BarPointersEncoding.Set) {
          let _serie = frontRepo.Series.get(_id)
          if (_serie != undefined) {
            bardb.Set.push(_serie!)
          }
        }
        // this.log(`updated bardb id=${bardb.ID}`)
      }),
      catchError(this.handleError<BarDB>('updateBar'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in BarService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("BarService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
