// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { HelloDB } from './hello-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class HelloService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  HelloServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private hellosUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.hellosUrl = origin + '/api/gongd3/go/v1/hellos';
  }

  /** GET hellos from the server */
  getHellos(): Observable<HelloDB[]> {
    return this.http.get<HelloDB[]>(this.hellosUrl)
      .pipe(
        tap(_ => this.log('fetched hellos')),
        catchError(this.handleError<HelloDB[]>('getHellos', []))
      );
  }

  /** GET hello by id. Will 404 if id not found */
  getHello(id: number): Observable<HelloDB> {
    const url = `${this.hellosUrl}/${id}`;
    return this.http.get<HelloDB>(url).pipe(
      tap(_ => this.log(`fetched hello id=${id}`)),
      catchError(this.handleError<HelloDB>(`getHello id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new hello to the server */
  postHello(hellodb: HelloDB): Observable<HelloDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.post<HelloDB>(this.hellosUrl, hellodb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`posted hellodb id=${hellodb.ID}`)
      }),
      catchError(this.handleError<HelloDB>('postHello'))
    );
  }

  /** DELETE: delete the hellodb from the server */
  deleteHello(hellodb: HelloDB | number): Observable<HelloDB> {
    const id = typeof hellodb === 'number' ? hellodb : hellodb.ID;
    const url = `${this.hellosUrl}/${id}`;

    return this.http.delete<HelloDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted hellodb id=${id}`)),
      catchError(this.handleError<HelloDB>('deleteHello'))
    );
  }

  /** PUT: update the hellodb on the server */
  updateHello(hellodb: HelloDB): Observable<HelloDB> {
    const id = typeof hellodb === 'number' ? hellodb : hellodb.ID;
    const url = `${this.hellosUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put<HelloDB>(url, hellodb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated hellodb id=${hellodb.ID}`)
      }),
      catchError(this.handleError<HelloDB>('updateHello'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
