// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { KeyDB } from './key-db';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class KeyService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  KeyServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private keysUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.keysUrl = origin + '/api/github.com/fullstack-lang/gongd3/go/v1/keys';
  }

  /** GET keys from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string): Observable<KeyDB[]> {
    return this.getKeys(GONG__StackPath)
  }
  getKeys(GONG__StackPath: string): Observable<KeyDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<KeyDB[]>(this.keysUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched keys')),
        catchError(this.handleError<KeyDB[]>('getKeys', []))
      );
  }

  /** GET key by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string): Observable<KeyDB> {
	return this.getKey(id, GONG__StackPath)
  }
  getKey(id: number, GONG__StackPath: string): Observable<KeyDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.keysUrl}/${id}`;
    return this.http.get<KeyDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched key id=${id}`)),
      catchError(this.handleError<KeyDB>(`getKey id=${id}`))
    );
  }

  /** POST: add a new key to the server */
  post(keydb: KeyDB, GONG__StackPath: string): Observable<KeyDB> {
    return this.postKey(keydb, GONG__StackPath)	
  }
  postKey(keydb: KeyDB, GONG__StackPath: string): Observable<KeyDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<KeyDB>(this.keysUrl, keydb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`posted keydb id=${keydb.ID}`)
      }),
      catchError(this.handleError<KeyDB>('postKey'))
    );
  }

  /** DELETE: delete the keydb from the server */
  delete(keydb: KeyDB | number, GONG__StackPath: string): Observable<KeyDB> {
    return this.deleteKey(keydb, GONG__StackPath)
  }
  deleteKey(keydb: KeyDB | number, GONG__StackPath: string): Observable<KeyDB> {
    const id = typeof keydb === 'number' ? keydb : keydb.ID;
    const url = `${this.keysUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<KeyDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted keydb id=${id}`)),
      catchError(this.handleError<KeyDB>('deleteKey'))
    );
  }

  /** PUT: update the keydb on the server */
  update(keydb: KeyDB, GONG__StackPath: string): Observable<KeyDB> {
    return this.updateKey(keydb, GONG__StackPath)
  }
  updateKey(keydb: KeyDB, GONG__StackPath: string): Observable<KeyDB> {
    const id = typeof keydb === 'number' ? keydb : keydb.ID;
    const url = `${this.keysUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<KeyDB>(url, keydb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        // this.log(`updated keydb id=${keydb.ID}`)
      }),
      catchError(this.handleError<KeyDB>('updateKey'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in KeyService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("KeyService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
