// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { PieDB } from './pie-db';

// insertion point for imports
import { KeyDB } from './key-db'

@Injectable({
  providedIn: 'root'
})
export class PieService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  PieServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private piesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.piesUrl = origin + '/api/github.com/fullstack-lang/gongd3/go/v1/pies';
  }

  /** GET pies from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string): Observable<PieDB[]> {
    return this.getPies(GONG__StackPath)
  }
  getPies(GONG__StackPath: string): Observable<PieDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<PieDB[]>(this.piesUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched pies')),
        catchError(this.handleError<PieDB[]>('getPies', []))
      );
  }

  /** GET pie by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string): Observable<PieDB> {
	return this.getPie(id, GONG__StackPath)
  }
  getPie(id: number, GONG__StackPath: string): Observable<PieDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.piesUrl}/${id}`;
    return this.http.get<PieDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched pie id=${id}`)),
      catchError(this.handleError<PieDB>(`getPie id=${id}`))
    );
  }

  /** POST: add a new pie to the server */
  post(piedb: PieDB, GONG__StackPath: string): Observable<PieDB> {
    return this.postPie(piedb, GONG__StackPath)	
  }
  postPie(piedb: PieDB, GONG__StackPath: string): Observable<PieDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let X = piedb.X
    piedb.X = new KeyDB
    let Y = piedb.Y
    piedb.Y = new KeyDB
    let Set = piedb.Set
    piedb.Set = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<PieDB>(this.piesUrl, piedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
	      piedb.Set = Set
        // this.log(`posted piedb id=${piedb.ID}`)
      }),
      catchError(this.handleError<PieDB>('postPie'))
    );
  }

  /** DELETE: delete the piedb from the server */
  delete(piedb: PieDB | number, GONG__StackPath: string): Observable<PieDB> {
    return this.deletePie(piedb, GONG__StackPath)
  }
  deletePie(piedb: PieDB | number, GONG__StackPath: string): Observable<PieDB> {
    const id = typeof piedb === 'number' ? piedb : piedb.ID;
    const url = `${this.piesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<PieDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted piedb id=${id}`)),
      catchError(this.handleError<PieDB>('deletePie'))
    );
  }

  /** PUT: update the piedb on the server */
  update(piedb: PieDB, GONG__StackPath: string): Observable<PieDB> {
    return this.updatePie(piedb, GONG__StackPath)
  }
  updatePie(piedb: PieDB, GONG__StackPath: string): Observable<PieDB> {
    const id = typeof piedb === 'number' ? piedb : piedb.ID;
    const url = `${this.piesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let X = piedb.X
    piedb.X = new KeyDB
    let Y = piedb.Y
    piedb.Y = new KeyDB
    let Set = piedb.Set
    piedb.Set = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<PieDB>(url, piedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
	      piedb.Set = Set
        // this.log(`updated piedb id=${piedb.ID}`)
      }),
      catchError(this.handleError<PieDB>('updatePie'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in PieService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("PieService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
