// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ScatterDB } from './scatter-db';

// insertion point for imports
import { KeyDB } from './key-db'

@Injectable({
  providedIn: 'root'
})
export class ScatterService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ScatterServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private scattersUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.scattersUrl = origin + '/api/github.com/fullstack-lang/gongd3/go/v1/scatters';
  }

  /** GET scatters from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string): Observable<ScatterDB[]> {
    return this.getScatters(GONG__StackPath)
  }
  getScatters(GONG__StackPath: string): Observable<ScatterDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ScatterDB[]>(this.scattersUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched scatters')),
        catchError(this.handleError<ScatterDB[]>('getScatters', []))
      );
  }

  /** GET scatter by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string): Observable<ScatterDB> {
	return this.getScatter(id, GONG__StackPath)
  }
  getScatter(id: number, GONG__StackPath: string): Observable<ScatterDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.scattersUrl}/${id}`;
    return this.http.get<ScatterDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched scatter id=${id}`)),
      catchError(this.handleError<ScatterDB>(`getScatter id=${id}`))
    );
  }

  /** POST: add a new scatter to the server */
  post(scatterdb: ScatterDB, GONG__StackPath: string): Observable<ScatterDB> {
    return this.postScatter(scatterdb, GONG__StackPath)	
  }
  postScatter(scatterdb: ScatterDB, GONG__StackPath: string): Observable<ScatterDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let X = scatterdb.X
    scatterdb.X = new KeyDB
    let Y = scatterdb.Y
    scatterdb.Y = new KeyDB
    let Text = scatterdb.Text
    scatterdb.Text = new KeyDB
    let Set = scatterdb.Set
    scatterdb.Set = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ScatterDB>(this.scattersUrl, scatterdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
	      scatterdb.Set = Set
        // this.log(`posted scatterdb id=${scatterdb.ID}`)
      }),
      catchError(this.handleError<ScatterDB>('postScatter'))
    );
  }

  /** DELETE: delete the scatterdb from the server */
  delete(scatterdb: ScatterDB | number, GONG__StackPath: string): Observable<ScatterDB> {
    return this.deleteScatter(scatterdb, GONG__StackPath)
  }
  deleteScatter(scatterdb: ScatterDB | number, GONG__StackPath: string): Observable<ScatterDB> {
    const id = typeof scatterdb === 'number' ? scatterdb : scatterdb.ID;
    const url = `${this.scattersUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ScatterDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted scatterdb id=${id}`)),
      catchError(this.handleError<ScatterDB>('deleteScatter'))
    );
  }

  /** PUT: update the scatterdb on the server */
  update(scatterdb: ScatterDB, GONG__StackPath: string): Observable<ScatterDB> {
    return this.updateScatter(scatterdb, GONG__StackPath)
  }
  updateScatter(scatterdb: ScatterDB, GONG__StackPath: string): Observable<ScatterDB> {
    const id = typeof scatterdb === 'number' ? scatterdb : scatterdb.ID;
    const url = `${this.scattersUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let X = scatterdb.X
    scatterdb.X = new KeyDB
    let Y = scatterdb.Y
    scatterdb.Y = new KeyDB
    let Text = scatterdb.Text
    scatterdb.Text = new KeyDB
    let Set = scatterdb.Set
    scatterdb.Set = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ScatterDB>(url, scatterdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
	      scatterdb.Set = Set
        // this.log(`updated scatterdb id=${scatterdb.ID}`)
      }),
      catchError(this.handleError<ScatterDB>('updateScatter'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ScatterService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ScatterService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
      console.log(message)
  }
}
