// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { SerieDB } from './serie-db';

// insertion point for imports
import { KeyDB } from './key-db'
import { BarDB } from './bar-db'
import { PieDB } from './pie-db'
import { ScatterDB } from './scatter-db'

@Injectable({
  providedIn: 'root'
})
export class SerieService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  SerieServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private seriesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.seriesUrl = origin + '/api/gongd3/go/v1/series';
  }

  /** GET series from the server */
  getSeries(GONG__StackPath: string = ""): Observable<SerieDB[]> {

	let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<SerieDB[]>(this.seriesUrl, { params: params })
      .pipe(
        tap(_ => this.log('fetched series')),
        catchError(this.handleError<SerieDB[]>('getSeries', []))
      );
  }

  /** GET serie by id. Will 404 if id not found */
  getSerie(id: number): Observable<SerieDB> {
    const url = `${this.seriesUrl}/${id}`;
    return this.http.get<SerieDB>(url).pipe(
      tap(_ => this.log(`fetched serie id=${id}`)),
      catchError(this.handleError<SerieDB>(`getSerie id=${id}`))
    );
  }

  /** POST: add a new serie to the server */
  postSerie(seriedb: SerieDB, GONG__StackPath: string): Observable<SerieDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    seriedb.Key = new KeyDB
    seriedb.Values = []
    let _Bar_Set_reverse = seriedb.Bar_Set_reverse
    seriedb.Bar_Set_reverse = new BarDB
    let _Pie_Set_reverse = seriedb.Pie_Set_reverse
    seriedb.Pie_Set_reverse = new PieDB
    let _Scatter_Set_reverse = seriedb.Scatter_Set_reverse
    seriedb.Scatter_Set_reverse = new ScatterDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

	return this.http.post<SerieDB>(this.seriesUrl, seriedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        seriedb.Bar_Set_reverse = _Bar_Set_reverse
        seriedb.Pie_Set_reverse = _Pie_Set_reverse
        seriedb.Scatter_Set_reverse = _Scatter_Set_reverse
        this.log(`posted seriedb id=${seriedb.ID}`)
      }),
      catchError(this.handleError<SerieDB>('postSerie'))
    );
  }

  /** DELETE: delete the seriedb from the server */
  deleteSerie(seriedb: SerieDB | number, GONG__StackPath: string): Observable<SerieDB> {
    const id = typeof seriedb === 'number' ? seriedb : seriedb.ID;
    const url = `${this.seriesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<SerieDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted seriedb id=${id}`)),
      catchError(this.handleError<SerieDB>('deleteSerie'))
    );
  }

  /** PUT: update the seriedb on the server */
  updateSerie(seriedb: SerieDB, GONG__StackPath: string): Observable<SerieDB> {
    const id = typeof seriedb === 'number' ? seriedb : seriedb.ID;
    const url = `${this.seriesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    seriedb.Key = new KeyDB
    seriedb.Values = []
    let _Bar_Set_reverse = seriedb.Bar_Set_reverse
    seriedb.Bar_Set_reverse = new BarDB
    let _Pie_Set_reverse = seriedb.Pie_Set_reverse
    seriedb.Pie_Set_reverse = new PieDB
    let _Scatter_Set_reverse = seriedb.Scatter_Set_reverse
    seriedb.Scatter_Set_reverse = new ScatterDB

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<SerieDB>(url, seriedb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        seriedb.Bar_Set_reverse = _Bar_Set_reverse
        seriedb.Pie_Set_reverse = _Pie_Set_reverse
        seriedb.Scatter_Set_reverse = _Scatter_Set_reverse
        this.log(`updated seriedb id=${seriedb.ID}`)
      }),
      catchError(this.handleError<SerieDB>('updateSerie'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
