// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { ValueDB } from './value-db';

// insertion point for imports
import { SerieDB } from './serie-db'

@Injectable({
  providedIn: 'root'
})
export class ValueService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ValueServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private valuesUrl: string

  constructor(
    private http: HttpClient,
    private location: Location,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.valuesUrl = origin + '/api/gongd3/go/v1/values';
  }

  /** GET values from the server */
  getValues(GONG__StackPath: string = ""): Observable<ValueDB[]> {

	let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ValueDB[]>(this.valuesUrl, { params: params })
      .pipe(
        tap(_ => this.log('fetched values')),
        catchError(this.handleError<ValueDB[]>('getValues', []))
      );
  }

  /** GET value by id. Will 404 if id not found */
  getValue(id: number): Observable<ValueDB> {
    const url = `${this.valuesUrl}/${id}`;
    return this.http.get<ValueDB>(url).pipe(
      tap(_ => this.log(`fetched value id=${id}`)),
      catchError(this.handleError<ValueDB>(`getValue id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new value to the server */
  postValue(valuedb: ValueDB): Observable<ValueDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let _Serie_Values_reverse = valuedb.Serie_Values_reverse
    valuedb.Serie_Values_reverse = new SerieDB

    return this.http.post<ValueDB>(this.valuesUrl, valuedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        valuedb.Serie_Values_reverse = _Serie_Values_reverse
        this.log(`posted valuedb id=${valuedb.ID}`)
      }),
      catchError(this.handleError<ValueDB>('postValue'))
    );
  }

  /** DELETE: delete the valuedb from the server */
  deleteValue(valuedb: ValueDB | number): Observable<ValueDB> {
    const id = typeof valuedb === 'number' ? valuedb : valuedb.ID;
    const url = `${this.valuesUrl}/${id}`;

    return this.http.delete<ValueDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted valuedb id=${id}`)),
      catchError(this.handleError<ValueDB>('deleteValue'))
    );
  }

  /** PUT: update the valuedb on the server */
  updateValue(valuedb: ValueDB): Observable<ValueDB> {
    const id = typeof valuedb === 'number' ? valuedb : valuedb.ID;
    const url = `${this.valuesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    let _Serie_Values_reverse = valuedb.Serie_Values_reverse
    valuedb.Serie_Values_reverse = new SerieDB

    return this.http.put<ValueDB>(url, valuedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        valuedb.Serie_Values_reverse = _Serie_Values_reverse
        this.log(`updated valuedb id=${valuedb.ID}`)
      }),
      catchError(this.handleError<ValueDB>('updateValue'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
