// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { ScatterDB } from '../scatter-db'
import { ScatterService } from '../scatter.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-scatterstable',
  templateUrl: './scatters-table.component.html',
  styleUrls: ['./scatters-table.component.css'],
})
export class ScattersTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Scatter instances
  selection: SelectionModel<ScatterDB> = new (SelectionModel)
  initialSelection = new Array<ScatterDB>()

  // the data source for the table
  scatters: ScatterDB[] = []
  matTableDataSource: MatTableDataSource<ScatterDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.scatters
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (scatterDB: ScatterDB, property: string) => {
      switch (property) {
        case 'ID':
          return scatterDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return scatterDB.Name;

        case 'X':
          return (scatterDB.X ? scatterDB.X.Name : '');

        case 'Y':
          return (scatterDB.Y ? scatterDB.Y.Name : '');

        case 'Text':
          return (scatterDB.Text ? scatterDB.Text.Name : '');

        case 'Width':
          return scatterDB.Width;

        case 'Heigth':
          return scatterDB.Heigth;

        case 'Margin':
          return scatterDB.Margin;

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (scatterDB: ScatterDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the scatterDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += scatterDB.Name.toLowerCase()
      if (scatterDB.X) {
        mergedContent += scatterDB.X.Name.toLowerCase()
      }
      if (scatterDB.Y) {
        mergedContent += scatterDB.Y.Name.toLowerCase()
      }
      if (scatterDB.Text) {
        mergedContent += scatterDB.Text.Name.toLowerCase()
      }
      mergedContent += scatterDB.Width.toString()
      mergedContent += scatterDB.Heigth.toString()
      mergedContent += scatterDB.Margin.toString()

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private scatterService: ScatterService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of scatter instances
    public dialogRef: MatDialogRef<ScattersTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.scatterService.ScatterServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getScatters()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "Text",
        "Width",
        "Heigth",
        "Margin",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "X",
        "Y",
        "Text",
        "Width",
        "Heigth",
        "Margin",
      ]
      this.selection = new SelectionModel<ScatterDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if ( stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getScatters()

    this.matTableDataSource = new MatTableDataSource(this.scatters)
  }

  getScatters(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.scatters = this.frontRepo.Scatters_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let scatter of this.scatters) {
            let ID = this.dialogData.ID
            let revPointer = scatter[this.dialogData.ReversePointer as keyof ScatterDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(scatter)
            }
            this.selection = new SelectionModel<ScatterDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ScatterDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          let sourceField = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as ScatterDB[]
          for (let associationInstance of sourceField) {
            let scatter = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ScatterDB
            this.initialSelection.push(scatter)
          }

          this.selection = new SelectionModel<ScatterDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.scatters
      }
    )
  }

  // newScatter initiate a new scatter
  // create a new Scatter objet
  newScatter() {
  }

  deleteScatter(scatterID: number, scatter: ScatterDB) {
    // list of scatters is truncated of scatter before the delete
    this.scatters = this.scatters.filter(h => h !== scatter);

    this.scatterService.deleteScatter(scatterID).subscribe(
      scatter => {
        this.scatterService.ScatterServiceChanged.next("delete")
      }
    );
  }

  editScatter(scatterID: number, scatter: ScatterDB) {

  }

  // display scatter in router
  displayScatterInRouter(scatterID: number) {
    this.router.navigate(["gongd3_go-" + "scatter-display", scatterID])
  }

  // set editor outlet
  setEditorRouterOutlet(scatterID: number) {
    this.router.navigate([{
      outlets: {
        gongd3_go_editor: ["gongd3_go-" + "scatter-detail", scatterID, this.GONG__StackPath]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.scatters.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.scatters.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<ScatterDB>()

      // reset all initial selection of scatter that belong to scatter
      for (let scatter of this.initialSelection) {
        let index = scatter[this.dialogData.ReversePointer as keyof ScatterDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(scatter)

      }

      // from selection, set scatter that belong to scatter
      for (let scatter of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = scatter[this.dialogData.ReversePointer as keyof ScatterDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(scatter)
      }


      // update all scatter (only update selection & initial selection)
      for (let scatter of toUpdate) {
        this.scatterService.updateScatter(scatter)
          .subscribe(scatter => {
            this.scatterService.ScatterServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, ScatterDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedScatter = new Set<number>()
      for (let scatter of this.initialSelection) {
        if (this.selection.selected.includes(scatter)) {
          // console.log("scatter " + scatter.Name + " is still selected")
        } else {
          console.log("scatter " + scatter.Name + " has been unselected")
          unselectedScatter.add(scatter.ID)
          console.log("is unselected " + unselectedScatter.has(scatter.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let scatter = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as ScatterDB
      if (unselectedScatter.has(scatter.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<ScatterDB>) = new Array<ScatterDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          scatter => {
            if (!this.initialSelection.includes(scatter)) {
              // console.log("scatter " + scatter.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + scatter.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = scatter.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = scatter.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("scatter " + scatter.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<ScatterDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
