// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { PieAPI } from './pie-api'
import { Pie, CopyPieToPieAPI } from './pie'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { KeyAPI } from './key-api'
import { SerieAPI } from './serie-api'

@Injectable({
  providedIn: 'root'
})
export class PieService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  PieServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private piesUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.piesUrl = origin + '/api/github.com/fullstack-lang/gongd3/go/v1/pies';
  }

  /** GET pies from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI[]> {
    return this.getPies(GONG__StackPath, frontRepo)
  }
  getPies(GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<PieAPI[]>(this.piesUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<PieAPI[]>('getPies', []))
      );
  }

  /** GET pie by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI> {
    return this.getPie(id, GONG__StackPath, frontRepo)
  }
  getPie(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.piesUrl}/${id}`;
    return this.http.get<PieAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched pie id=${id}`)),
      catchError(this.handleError<PieAPI>(`getPie id=${id}`))
    );
  }

  // postFront copy pie to a version with encoded pointers and post to the back
  postFront(pie: Pie, GONG__StackPath: string): Observable<PieAPI> {
    let pieAPI = new PieAPI
    CopyPieToPieAPI(pie, pieAPI)
    const id = typeof pieAPI === 'number' ? pieAPI : pieAPI.ID
    const url = `${this.piesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<PieAPI>(url, pieAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<PieAPI>('postPie'))
    );
  }
  
  /** POST: add a new pie to the server */
  post(piedb: PieAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI> {
    return this.postPie(piedb, GONG__StackPath, frontRepo)
  }
  postPie(piedb: PieAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<PieAPI>(this.piesUrl, piedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted piedb id=${piedb.ID}`)
      }),
      catchError(this.handleError<PieAPI>('postPie'))
    );
  }

  /** DELETE: delete the piedb from the server */
  delete(piedb: PieAPI | number, GONG__StackPath: string): Observable<PieAPI> {
    return this.deletePie(piedb, GONG__StackPath)
  }
  deletePie(piedb: PieAPI | number, GONG__StackPath: string): Observable<PieAPI> {
    const id = typeof piedb === 'number' ? piedb : piedb.ID;
    const url = `${this.piesUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<PieAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted piedb id=${id}`)),
      catchError(this.handleError<PieAPI>('deletePie'))
    );
  }

  // updateFront copy pie to a version with encoded pointers and update to the back
  updateFront(pie: Pie, GONG__StackPath: string): Observable<PieAPI> {
    let pieAPI = new PieAPI
    CopyPieToPieAPI(pie, pieAPI)
    const id = typeof pieAPI === 'number' ? pieAPI : pieAPI.ID
    const url = `${this.piesUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<PieAPI>(url, pieAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<PieAPI>('updatePie'))
    );
  }

  /** PUT: update the piedb on the server */
  update(piedb: PieAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI> {
    return this.updatePie(piedb, GONG__StackPath, frontRepo)
  }
  updatePie(piedb: PieAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<PieAPI> {
    const id = typeof piedb === 'number' ? piedb : piedb.ID;
    const url = `${this.piesUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<PieAPI>(url, piedb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated piedb id=${piedb.ID}`)
      }),
      catchError(this.handleError<PieAPI>('updatePie'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in PieService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("PieService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
