// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { ScatterAPI } from './scatter-api'
import { Scatter, CopyScatterToScatterAPI } from './scatter'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { KeyAPI } from './key-api'
import { SerieAPI } from './serie-api'

@Injectable({
  providedIn: 'root'
})
export class ScatterService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  ScatterServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private scattersUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.scattersUrl = origin + '/api/github.com/fullstack-lang/gongd3/go/v1/scatters';
  }

  /** GET scatters from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI[]> {
    return this.getScatters(GONG__StackPath, frontRepo)
  }
  getScatters(GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<ScatterAPI[]>(this.scattersUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<ScatterAPI[]>('getScatters', []))
      );
  }

  /** GET scatter by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI> {
    return this.getScatter(id, GONG__StackPath, frontRepo)
  }
  getScatter(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.scattersUrl}/${id}`;
    return this.http.get<ScatterAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched scatter id=${id}`)),
      catchError(this.handleError<ScatterAPI>(`getScatter id=${id}`))
    );
  }

  // postFront copy scatter to a version with encoded pointers and post to the back
  postFront(scatter: Scatter, GONG__StackPath: string): Observable<ScatterAPI> {
    let scatterAPI = new ScatterAPI
    CopyScatterToScatterAPI(scatter, scatterAPI)
    const id = typeof scatterAPI === 'number' ? scatterAPI : scatterAPI.ID
    const url = `${this.scattersUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ScatterAPI>(url, scatterAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ScatterAPI>('postScatter'))
    );
  }
  
  /** POST: add a new scatter to the server */
  post(scatterdb: ScatterAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI> {
    return this.postScatter(scatterdb, GONG__StackPath, frontRepo)
  }
  postScatter(scatterdb: ScatterAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<ScatterAPI>(this.scattersUrl, scatterdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted scatterdb id=${scatterdb.ID}`)
      }),
      catchError(this.handleError<ScatterAPI>('postScatter'))
    );
  }

  /** DELETE: delete the scatterdb from the server */
  delete(scatterdb: ScatterAPI | number, GONG__StackPath: string): Observable<ScatterAPI> {
    return this.deleteScatter(scatterdb, GONG__StackPath)
  }
  deleteScatter(scatterdb: ScatterAPI | number, GONG__StackPath: string): Observable<ScatterAPI> {
    const id = typeof scatterdb === 'number' ? scatterdb : scatterdb.ID;
    const url = `${this.scattersUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<ScatterAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted scatterdb id=${id}`)),
      catchError(this.handleError<ScatterAPI>('deleteScatter'))
    );
  }

  // updateFront copy scatter to a version with encoded pointers and update to the back
  updateFront(scatter: Scatter, GONG__StackPath: string): Observable<ScatterAPI> {
    let scatterAPI = new ScatterAPI
    CopyScatterToScatterAPI(scatter, scatterAPI)
    const id = typeof scatterAPI === 'number' ? scatterAPI : scatterAPI.ID
    const url = `${this.scattersUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<ScatterAPI>(url, scatterAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<ScatterAPI>('updateScatter'))
    );
  }

  /** PUT: update the scatterdb on the server */
  update(scatterdb: ScatterAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI> {
    return this.updateScatter(scatterdb, GONG__StackPath, frontRepo)
  }
  updateScatter(scatterdb: ScatterAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<ScatterAPI> {
    const id = typeof scatterdb === 'number' ? scatterdb : scatterdb.ID;
    const url = `${this.scattersUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<ScatterAPI>(url, scatterdb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated scatterdb id=${scatterdb.ID}`)
      }),
      catchError(this.handleError<ScatterAPI>('updateScatter'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in ScatterService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("ScatterService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
