// generated by ModelGongFileTemplate
package models

import (
	"errors"
	"fmt"
	"log"
	"os"
	"path"
	"regexp"
	"sort"
	"strings"
)

// errUnkownEnum is returns when a value cannot match enum values
var errUnkownEnum = errors.New("unkown enum")

// swagger:ignore
type __void any

// needed for creating set of instances in the stage
var __member __void

// GongStructInterface is the interface met by GongStructs
// It allows runtime reflexion of instances (without the hassle of the "reflect" package)
type GongStructInterface interface {
	GetName() (res string)
	GetFields() (res []string)
	GetFieldStringValue(fieldName string) (res string)
}

// StageStruct enables storage of staged instances
// swagger:ignore
type StageStruct struct { // insertion point for definition of arrays registering instances
	Bars           map[*Bar]any
	Bars_mapString map[string]*Bar

	OnAfterBarCreateCallback OnAfterCreateInterface[Bar]
	OnAfterBarUpdateCallback OnAfterUpdateInterface[Bar]
	OnAfterBarDeleteCallback OnAfterDeleteInterface[Bar]
	OnAfterBarReadCallback   OnAfterReadInterface[Bar]

	Keys           map[*Key]any
	Keys_mapString map[string]*Key

	OnAfterKeyCreateCallback OnAfterCreateInterface[Key]
	OnAfterKeyUpdateCallback OnAfterUpdateInterface[Key]
	OnAfterKeyDeleteCallback OnAfterDeleteInterface[Key]
	OnAfterKeyReadCallback   OnAfterReadInterface[Key]

	Pies           map[*Pie]any
	Pies_mapString map[string]*Pie

	OnAfterPieCreateCallback OnAfterCreateInterface[Pie]
	OnAfterPieUpdateCallback OnAfterUpdateInterface[Pie]
	OnAfterPieDeleteCallback OnAfterDeleteInterface[Pie]
	OnAfterPieReadCallback   OnAfterReadInterface[Pie]

	Series           map[*Serie]any
	Series_mapString map[string]*Serie

	OnAfterSerieCreateCallback OnAfterCreateInterface[Serie]
	OnAfterSerieUpdateCallback OnAfterUpdateInterface[Serie]
	OnAfterSerieDeleteCallback OnAfterDeleteInterface[Serie]
	OnAfterSerieReadCallback   OnAfterReadInterface[Serie]

	Values           map[*Value]any
	Values_mapString map[string]*Value

	OnAfterValueCreateCallback OnAfterCreateInterface[Value]
	OnAfterValueUpdateCallback OnAfterUpdateInterface[Value]
	OnAfterValueDeleteCallback OnAfterDeleteInterface[Value]
	OnAfterValueReadCallback   OnAfterReadInterface[Value]

	AllModelsStructCreateCallback AllModelsStructCreateInterface

	AllModelsStructDeleteCallback AllModelsStructDeleteInterface

	BackRepo BackRepoInterface

	// if set will be called before each commit to the back repo
	OnInitCommitCallback          OnInitCommitInterface
	OnInitCommitFromFrontCallback OnInitCommitInterface
	OnInitCommitFromBackCallback  OnInitCommitInterface

	// store the number of instance per gongstruct
	Map_GongStructName_InstancesNb map[string]int
}

type OnInitCommitInterface interface {
	BeforeCommit(stage *StageStruct)
}

// OnAfterCreateInterface callback when an instance is updated from the front
type OnAfterCreateInterface[Type Gongstruct] interface {
	OnAfterCreate(stage *StageStruct,
		instance *Type)
}

// OnAfterReadInterface callback when an instance is updated from the front
type OnAfterReadInterface[Type Gongstruct] interface {
	OnAfterRead(stage *StageStruct,
		instance *Type)
}

// OnAfterUpdateInterface callback when an instance is updated from the front
type OnAfterUpdateInterface[Type Gongstruct] interface {
	OnAfterUpdate(stage *StageStruct, old, new *Type)
}

// OnAfterDeleteInterface callback when an instance is updated from the front
type OnAfterDeleteInterface[Type Gongstruct] interface {
	OnAfterDelete(stage *StageStruct,
		staged, front *Type)
}

type BackRepoInterface interface {
	Commit(stage *StageStruct)
	Checkout(stage *StageStruct)
	Backup(stage *StageStruct, dirPath string)
	Restore(stage *StageStruct, dirPath string)
	BackupXL(stage *StageStruct, dirPath string)
	RestoreXL(stage *StageStruct, dirPath string)
	// insertion point for Commit and Checkout signatures
	CommitBar(bar *Bar)
	CheckoutBar(bar *Bar)
	CommitKey(key *Key)
	CheckoutKey(key *Key)
	CommitPie(pie *Pie)
	CheckoutPie(pie *Pie)
	CommitSerie(serie *Serie)
	CheckoutSerie(serie *Serie)
	CommitValue(value *Value)
	CheckoutValue(value *Value)
	GetLastCommitFromBackNb() uint
	GetLastPushFromFrontNb() uint
}

// swagger:ignore instructs the gong compiler (gongc) to avoid this particular struct
var Stage StageStruct = StageStruct{ // insertion point for array initiatialisation
	Bars:           make(map[*Bar]any),
	Bars_mapString: make(map[string]*Bar),

	Keys:           make(map[*Key]any),
	Keys_mapString: make(map[string]*Key),

	Pies:           make(map[*Pie]any),
	Pies_mapString: make(map[string]*Pie),

	Series:           make(map[*Serie]any),
	Series_mapString: make(map[string]*Serie),

	Values:           make(map[*Value]any),
	Values_mapString: make(map[string]*Value),

	// end of insertion point
	Map_GongStructName_InstancesNb: make(map[string]int),
}

func (stage *StageStruct) Commit() {
	if stage.BackRepo != nil {
		stage.BackRepo.Commit(stage)
	}

	// insertion point for computing the map of number of instances per gongstruct
	stage.Map_GongStructName_InstancesNb["Bar"] = len(stage.Bars)
	stage.Map_GongStructName_InstancesNb["Key"] = len(stage.Keys)
	stage.Map_GongStructName_InstancesNb["Pie"] = len(stage.Pies)
	stage.Map_GongStructName_InstancesNb["Serie"] = len(stage.Series)
	stage.Map_GongStructName_InstancesNb["Value"] = len(stage.Values)

}

func (stage *StageStruct) Checkout() {
	if stage.BackRepo != nil {
		stage.BackRepo.Checkout(stage)
	}

	// insertion point for computing the map of number of instances per gongstruct
	stage.Map_GongStructName_InstancesNb["Bar"] = len(stage.Bars)
	stage.Map_GongStructName_InstancesNb["Key"] = len(stage.Keys)
	stage.Map_GongStructName_InstancesNb["Pie"] = len(stage.Pies)
	stage.Map_GongStructName_InstancesNb["Serie"] = len(stage.Series)
	stage.Map_GongStructName_InstancesNb["Value"] = len(stage.Values)

}

// backup generates backup files in the dirPath
func (stage *StageStruct) Backup(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.Backup(stage, dirPath)
	}
}

// Restore resets Stage & BackRepo and restores their content from the restore files in dirPath
func (stage *StageStruct) Restore(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.Restore(stage, dirPath)
	}
}

// backup generates backup files in the dirPath
func (stage *StageStruct) BackupXL(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.BackupXL(stage, dirPath)
	}
}

// Restore resets Stage & BackRepo and restores their content from the restore files in dirPath
func (stage *StageStruct) RestoreXL(dirPath string) {
	if stage.BackRepo != nil {
		stage.BackRepo.RestoreXL(stage, dirPath)
	}
}

// insertion point for cumulative sub template with model space calls
// Stage puts bar to the model stage
func (bar *Bar) Stage() *Bar {
	Stage.Bars[bar] = __member
	Stage.Bars_mapString[bar.Name] = bar

	return bar
}

// Unstage removes bar off the model stage
func (bar *Bar) Unstage() *Bar {
	delete(Stage.Bars, bar)
	delete(Stage.Bars_mapString, bar.Name)
	return bar
}

// commit bar to the back repo (if it is already staged)
func (bar *Bar) Commit() *Bar {
	if _, ok := Stage.Bars[bar]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitBar(bar)
		}
	}
	return bar
}

// Checkout bar to the back repo (if it is already staged)
func (bar *Bar) Checkout() *Bar {
	if _, ok := Stage.Bars[bar]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutBar(bar)
		}
	}
	return bar
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of bar to the model stage
func (bar *Bar) StageCopy() *Bar {
	_bar := new(Bar)
	*_bar = *bar
	_bar.Stage()
	return _bar
}

// StageAndCommit appends bar to the model stage and commit to the orm repo
func (bar *Bar) StageAndCommit() *Bar {
	bar.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMBar(bar)
	}
	return bar
}

// DeleteStageAndCommit appends bar to the model stage and commit to the orm repo
func (bar *Bar) DeleteStageAndCommit() *Bar {
	bar.Unstage()
	DeleteORMBar(bar)
	return bar
}

// StageCopyAndCommit appends a copy of bar to the model stage and commit to the orm repo
func (bar *Bar) StageCopyAndCommit() *Bar {
	_bar := new(Bar)
	*_bar = *bar
	_bar.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMBar(bar)
	}
	return _bar
}

// CreateORMBar enables dynamic staging of a Bar instance
func CreateORMBar(bar *Bar) {
	bar.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMBar(bar)
	}
}

// DeleteORMBar enables dynamic staging of a Bar instance
func DeleteORMBar(bar *Bar) {
	bar.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMBar(bar)
	}
}

// for satisfaction of GongStruct interface
func (bar *Bar) GetName() (res string) {
	return bar.Name
}

// Stage puts key to the model stage
func (key *Key) Stage() *Key {
	Stage.Keys[key] = __member
	Stage.Keys_mapString[key.Name] = key

	return key
}

// Unstage removes key off the model stage
func (key *Key) Unstage() *Key {
	delete(Stage.Keys, key)
	delete(Stage.Keys_mapString, key.Name)
	return key
}

// commit key to the back repo (if it is already staged)
func (key *Key) Commit() *Key {
	if _, ok := Stage.Keys[key]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitKey(key)
		}
	}
	return key
}

// Checkout key to the back repo (if it is already staged)
func (key *Key) Checkout() *Key {
	if _, ok := Stage.Keys[key]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutKey(key)
		}
	}
	return key
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of key to the model stage
func (key *Key) StageCopy() *Key {
	_key := new(Key)
	*_key = *key
	_key.Stage()
	return _key
}

// StageAndCommit appends key to the model stage and commit to the orm repo
func (key *Key) StageAndCommit() *Key {
	key.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMKey(key)
	}
	return key
}

// DeleteStageAndCommit appends key to the model stage and commit to the orm repo
func (key *Key) DeleteStageAndCommit() *Key {
	key.Unstage()
	DeleteORMKey(key)
	return key
}

// StageCopyAndCommit appends a copy of key to the model stage and commit to the orm repo
func (key *Key) StageCopyAndCommit() *Key {
	_key := new(Key)
	*_key = *key
	_key.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMKey(key)
	}
	return _key
}

// CreateORMKey enables dynamic staging of a Key instance
func CreateORMKey(key *Key) {
	key.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMKey(key)
	}
}

// DeleteORMKey enables dynamic staging of a Key instance
func DeleteORMKey(key *Key) {
	key.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMKey(key)
	}
}

// for satisfaction of GongStruct interface
func (key *Key) GetName() (res string) {
	return key.Name
}

// Stage puts pie to the model stage
func (pie *Pie) Stage() *Pie {
	Stage.Pies[pie] = __member
	Stage.Pies_mapString[pie.Name] = pie

	return pie
}

// Unstage removes pie off the model stage
func (pie *Pie) Unstage() *Pie {
	delete(Stage.Pies, pie)
	delete(Stage.Pies_mapString, pie.Name)
	return pie
}

// commit pie to the back repo (if it is already staged)
func (pie *Pie) Commit() *Pie {
	if _, ok := Stage.Pies[pie]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitPie(pie)
		}
	}
	return pie
}

// Checkout pie to the back repo (if it is already staged)
func (pie *Pie) Checkout() *Pie {
	if _, ok := Stage.Pies[pie]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutPie(pie)
		}
	}
	return pie
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of pie to the model stage
func (pie *Pie) StageCopy() *Pie {
	_pie := new(Pie)
	*_pie = *pie
	_pie.Stage()
	return _pie
}

// StageAndCommit appends pie to the model stage and commit to the orm repo
func (pie *Pie) StageAndCommit() *Pie {
	pie.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMPie(pie)
	}
	return pie
}

// DeleteStageAndCommit appends pie to the model stage and commit to the orm repo
func (pie *Pie) DeleteStageAndCommit() *Pie {
	pie.Unstage()
	DeleteORMPie(pie)
	return pie
}

// StageCopyAndCommit appends a copy of pie to the model stage and commit to the orm repo
func (pie *Pie) StageCopyAndCommit() *Pie {
	_pie := new(Pie)
	*_pie = *pie
	_pie.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMPie(pie)
	}
	return _pie
}

// CreateORMPie enables dynamic staging of a Pie instance
func CreateORMPie(pie *Pie) {
	pie.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMPie(pie)
	}
}

// DeleteORMPie enables dynamic staging of a Pie instance
func DeleteORMPie(pie *Pie) {
	pie.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMPie(pie)
	}
}

// for satisfaction of GongStruct interface
func (pie *Pie) GetName() (res string) {
	return pie.Name
}

// Stage puts serie to the model stage
func (serie *Serie) Stage() *Serie {
	Stage.Series[serie] = __member
	Stage.Series_mapString[serie.Name] = serie

	return serie
}

// Unstage removes serie off the model stage
func (serie *Serie) Unstage() *Serie {
	delete(Stage.Series, serie)
	delete(Stage.Series_mapString, serie.Name)
	return serie
}

// commit serie to the back repo (if it is already staged)
func (serie *Serie) Commit() *Serie {
	if _, ok := Stage.Series[serie]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitSerie(serie)
		}
	}
	return serie
}

// Checkout serie to the back repo (if it is already staged)
func (serie *Serie) Checkout() *Serie {
	if _, ok := Stage.Series[serie]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutSerie(serie)
		}
	}
	return serie
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of serie to the model stage
func (serie *Serie) StageCopy() *Serie {
	_serie := new(Serie)
	*_serie = *serie
	_serie.Stage()
	return _serie
}

// StageAndCommit appends serie to the model stage and commit to the orm repo
func (serie *Serie) StageAndCommit() *Serie {
	serie.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMSerie(serie)
	}
	return serie
}

// DeleteStageAndCommit appends serie to the model stage and commit to the orm repo
func (serie *Serie) DeleteStageAndCommit() *Serie {
	serie.Unstage()
	DeleteORMSerie(serie)
	return serie
}

// StageCopyAndCommit appends a copy of serie to the model stage and commit to the orm repo
func (serie *Serie) StageCopyAndCommit() *Serie {
	_serie := new(Serie)
	*_serie = *serie
	_serie.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMSerie(serie)
	}
	return _serie
}

// CreateORMSerie enables dynamic staging of a Serie instance
func CreateORMSerie(serie *Serie) {
	serie.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMSerie(serie)
	}
}

// DeleteORMSerie enables dynamic staging of a Serie instance
func DeleteORMSerie(serie *Serie) {
	serie.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMSerie(serie)
	}
}

// for satisfaction of GongStruct interface
func (serie *Serie) GetName() (res string) {
	return serie.Name
}

// Stage puts value to the model stage
func (value *Value) Stage() *Value {
	Stage.Values[value] = __member
	Stage.Values_mapString[value.Name] = value

	return value
}

// Unstage removes value off the model stage
func (value *Value) Unstage() *Value {
	delete(Stage.Values, value)
	delete(Stage.Values_mapString, value.Name)
	return value
}

// commit value to the back repo (if it is already staged)
func (value *Value) Commit() *Value {
	if _, ok := Stage.Values[value]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitValue(value)
		}
	}
	return value
}

// Checkout value to the back repo (if it is already staged)
func (value *Value) Checkout() *Value {
	if _, ok := Stage.Values[value]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutValue(value)
		}
	}
	return value
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of value to the model stage
func (value *Value) StageCopy() *Value {
	_value := new(Value)
	*_value = *value
	_value.Stage()
	return _value
}

// StageAndCommit appends value to the model stage and commit to the orm repo
func (value *Value) StageAndCommit() *Value {
	value.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMValue(value)
	}
	return value
}

// DeleteStageAndCommit appends value to the model stage and commit to the orm repo
func (value *Value) DeleteStageAndCommit() *Value {
	value.Unstage()
	DeleteORMValue(value)
	return value
}

// StageCopyAndCommit appends a copy of value to the model stage and commit to the orm repo
func (value *Value) StageCopyAndCommit() *Value {
	_value := new(Value)
	*_value = *value
	_value.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMValue(value)
	}
	return _value
}

// CreateORMValue enables dynamic staging of a Value instance
func CreateORMValue(value *Value) {
	value.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMValue(value)
	}
}

// DeleteORMValue enables dynamic staging of a Value instance
func DeleteORMValue(value *Value) {
	value.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMValue(value)
	}
}

// for satisfaction of GongStruct interface
func (value *Value) GetName() (res string) {
	return value.Name
}

// swagger:ignore
type AllModelsStructCreateInterface interface { // insertion point for Callbacks on creation
	CreateORMBar(Bar *Bar)
	CreateORMKey(Key *Key)
	CreateORMPie(Pie *Pie)
	CreateORMSerie(Serie *Serie)
	CreateORMValue(Value *Value)
}

type AllModelsStructDeleteInterface interface { // insertion point for Callbacks on deletion
	DeleteORMBar(Bar *Bar)
	DeleteORMKey(Key *Key)
	DeleteORMPie(Pie *Pie)
	DeleteORMSerie(Serie *Serie)
	DeleteORMValue(Value *Value)
}

func (stage *StageStruct) Reset() { // insertion point for array reset
	stage.Bars = make(map[*Bar]any)
	stage.Bars_mapString = make(map[string]*Bar)

	stage.Keys = make(map[*Key]any)
	stage.Keys_mapString = make(map[string]*Key)

	stage.Pies = make(map[*Pie]any)
	stage.Pies_mapString = make(map[string]*Pie)

	stage.Series = make(map[*Serie]any)
	stage.Series_mapString = make(map[string]*Serie)

	stage.Values = make(map[*Value]any)
	stage.Values_mapString = make(map[string]*Value)

}

func (stage *StageStruct) Nil() { // insertion point for array nil
	stage.Bars = nil
	stage.Bars_mapString = nil

	stage.Keys = nil
	stage.Keys_mapString = nil

	stage.Pies = nil
	stage.Pies_mapString = nil

	stage.Series = nil
	stage.Series_mapString = nil

	stage.Values = nil
	stage.Values_mapString = nil

}

const marshallRes = `package {{PackageName}}

import (
	"time"

	"{{ModelsPackageName}}"
)

// generated in order to avoid error in the package import
// if there are no elements in the stage to marshall
var ___dummy__Stage models.StageStruct
var ___dummy__Time time.Time

// init might be handy if one want to have the data embedded in the binary
// but it has to properly reference the Injection gateway in the main package
// func init() {
// 	_ = __Dummy_time_variable
// 	InjectionGateway["{{databaseName}}"] = {{databaseName}}Injection
// }

// {{databaseName}}Injection will stage objects of database "{{databaseName}}"
func {{databaseName}}Injection() {

	// Declaration of instances to stage{{Identifiers}}

	// Setup of values{{ValueInitializers}}

	// Setup of pointers{{PointersInitializers}}
}

`

const IdentifiersDecls = `
	{{Identifier}} := (&models.{{GeneratedStructName}}{Name: ` + "`" + `{{GeneratedFieldNameValue}}` + "`" + `}).Stage()`

const StringInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = ` + "`" + `{{GeneratedFieldNameValue}}` + "`"

const StringEnumInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const NumberInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const PointerFieldInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = {{GeneratedFieldNameValue}}`

const SliceOfPointersFieldInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}} = append({{Identifier}}.{{GeneratedFieldName}}, {{GeneratedFieldNameValue}})`

const TimeInitStatement = `
	{{Identifier}}.{{GeneratedFieldName}}, _ = time.Parse("2006-01-02 15:04:05.999999999 -0700 MST", "{{GeneratedFieldNameValue}}")`

// Marshall marshall the stage content into the file as an instanciation into a stage
func (stage *StageStruct) Marshall(file *os.File, modelsPackageName, packageName string) {

	name := file.Name()

	if !strings.HasSuffix(name, ".go") {
		log.Fatalln(name + " is not a go filename")
	}

	log.Println("filename of marshall output  is " + name)

	res := marshallRes
	res = strings.ReplaceAll(res, "{{databaseName}}", strings.ReplaceAll(path.Base(name), ".go", ""))
	res = strings.ReplaceAll(res, "{{PackageName}}", packageName)
	res = strings.ReplaceAll(res, "{{ModelsPackageName}}", modelsPackageName)

	// map of identifiers
	// var StageMapDstructIds map[*Dstruct]string
	identifiersDecl := ""
	initializerStatements := ""
	pointersInitializesStatements := ""

	id := ""
	decl := ""
	setValueField := ""

	// insertion initialization of objects to stage
	map_Bar_Identifiers := make(map[*Bar]string)
	_ = map_Bar_Identifiers

	barOrdered := []*Bar{}
	for bar := range stage.Bars {
		barOrdered = append(barOrdered, bar)
	}
	sort.Slice(barOrdered[:], func(i, j int) bool {
		return barOrdered[i].Name < barOrdered[j].Name
	})
	identifiersDecl += "\n\n	// Declarations of staged instances of Bar"
	for idx, bar := range barOrdered {

		id = generatesIdentifier("Bar", idx, bar.Name)
		map_Bar_Identifiers[bar] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Bar")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", bar.Name)
		identifiersDecl += decl

		initializerStatements += "\n\n	// Bar values setup"
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(bar.Name))
		initializerStatements += setValueField

		setValueField = NumberInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Width")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", fmt.Sprintf("%f", bar.Width))
		initializerStatements += setValueField

		setValueField = NumberInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Heigth")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", fmt.Sprintf("%f", bar.Heigth))
		initializerStatements += setValueField

		setValueField = NumberInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Margin")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", fmt.Sprintf("%f", bar.Margin))
		initializerStatements += setValueField

	}

	map_Key_Identifiers := make(map[*Key]string)
	_ = map_Key_Identifiers

	keyOrdered := []*Key{}
	for key := range stage.Keys {
		keyOrdered = append(keyOrdered, key)
	}
	sort.Slice(keyOrdered[:], func(i, j int) bool {
		return keyOrdered[i].Name < keyOrdered[j].Name
	})
	identifiersDecl += "\n\n	// Declarations of staged instances of Key"
	for idx, key := range keyOrdered {

		id = generatesIdentifier("Key", idx, key.Name)
		map_Key_Identifiers[key] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Key")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", key.Name)
		identifiersDecl += decl

		initializerStatements += "\n\n	// Key values setup"
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(key.Name))
		initializerStatements += setValueField

	}

	map_Pie_Identifiers := make(map[*Pie]string)
	_ = map_Pie_Identifiers

	pieOrdered := []*Pie{}
	for pie := range stage.Pies {
		pieOrdered = append(pieOrdered, pie)
	}
	sort.Slice(pieOrdered[:], func(i, j int) bool {
		return pieOrdered[i].Name < pieOrdered[j].Name
	})
	identifiersDecl += "\n\n	// Declarations of staged instances of Pie"
	for idx, pie := range pieOrdered {

		id = generatesIdentifier("Pie", idx, pie.Name)
		map_Pie_Identifiers[pie] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Pie")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", pie.Name)
		identifiersDecl += decl

		initializerStatements += "\n\n	// Pie values setup"
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(pie.Name))
		initializerStatements += setValueField

		setValueField = NumberInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Width")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", fmt.Sprintf("%f", pie.Width))
		initializerStatements += setValueField

		setValueField = NumberInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Heigth")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", fmt.Sprintf("%f", pie.Heigth))
		initializerStatements += setValueField

		setValueField = NumberInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Margin")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", fmt.Sprintf("%f", pie.Margin))
		initializerStatements += setValueField

	}

	map_Serie_Identifiers := make(map[*Serie]string)
	_ = map_Serie_Identifiers

	serieOrdered := []*Serie{}
	for serie := range stage.Series {
		serieOrdered = append(serieOrdered, serie)
	}
	sort.Slice(serieOrdered[:], func(i, j int) bool {
		return serieOrdered[i].Name < serieOrdered[j].Name
	})
	identifiersDecl += "\n\n	// Declarations of staged instances of Serie"
	for idx, serie := range serieOrdered {

		id = generatesIdentifier("Serie", idx, serie.Name)
		map_Serie_Identifiers[serie] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Serie")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", serie.Name)
		identifiersDecl += decl

		initializerStatements += "\n\n	// Serie values setup"
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(serie.Name))
		initializerStatements += setValueField

	}

	map_Value_Identifiers := make(map[*Value]string)
	_ = map_Value_Identifiers

	valueOrdered := []*Value{}
	for value := range stage.Values {
		valueOrdered = append(valueOrdered, value)
	}
	sort.Slice(valueOrdered[:], func(i, j int) bool {
		return valueOrdered[i].Name < valueOrdered[j].Name
	})
	identifiersDecl += "\n\n	// Declarations of staged instances of Value"
	for idx, value := range valueOrdered {

		id = generatesIdentifier("Value", idx, value.Name)
		map_Value_Identifiers[value] = id

		decl = IdentifiersDecls
		decl = strings.ReplaceAll(decl, "{{Identifier}}", id)
		decl = strings.ReplaceAll(decl, "{{GeneratedStructName}}", "Value")
		decl = strings.ReplaceAll(decl, "{{GeneratedFieldNameValue}}", value.Name)
		identifiersDecl += decl

		initializerStatements += "\n\n	// Value values setup"
		// Initialisation of values
		setValueField = StringInitStatement
		setValueField = strings.ReplaceAll(setValueField, "{{Identifier}}", id)
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldName}}", "Name")
		setValueField = strings.ReplaceAll(setValueField, "{{GeneratedFieldNameValue}}", string(value.Name))
		initializerStatements += setValueField

	}

	// insertion initialization of objects to stage
	for idx, bar := range barOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Bar", idx, bar.Name)
		map_Bar_Identifiers[bar] = id

		// Initialisation of values
		if bar.X != nil {
			setPointerField = PointerFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "X")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Key_Identifiers[bar.X])
			pointersInitializesStatements += setPointerField
		}

		if bar.Y != nil {
			setPointerField = PointerFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "Y")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Key_Identifiers[bar.Y])
			pointersInitializesStatements += setPointerField
		}

		for _, _serie := range bar.Set {
			setPointerField = SliceOfPointersFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "Set")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Serie_Identifiers[_serie])
			pointersInitializesStatements += setPointerField
		}

	}

	for idx, key := range keyOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Key", idx, key.Name)
		map_Key_Identifiers[key] = id

		// Initialisation of values
	}

	for idx, pie := range pieOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Pie", idx, pie.Name)
		map_Pie_Identifiers[pie] = id

		// Initialisation of values
		if pie.X != nil {
			setPointerField = PointerFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "X")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Key_Identifiers[pie.X])
			pointersInitializesStatements += setPointerField
		}

		if pie.Y != nil {
			setPointerField = PointerFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "Y")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Key_Identifiers[pie.Y])
			pointersInitializesStatements += setPointerField
		}

		for _, _serie := range pie.Set {
			setPointerField = SliceOfPointersFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "Set")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Serie_Identifiers[_serie])
			pointersInitializesStatements += setPointerField
		}

	}

	for idx, serie := range serieOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Serie", idx, serie.Name)
		map_Serie_Identifiers[serie] = id

		// Initialisation of values
		if serie.Key != nil {
			setPointerField = PointerFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "Key")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Key_Identifiers[serie.Key])
			pointersInitializesStatements += setPointerField
		}

		for _, _value := range serie.Values {
			setPointerField = SliceOfPointersFieldInitStatement
			setPointerField = strings.ReplaceAll(setPointerField, "{{Identifier}}", id)
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldName}}", "Values")
			setPointerField = strings.ReplaceAll(setPointerField, "{{GeneratedFieldNameValue}}", map_Value_Identifiers[_value])
			pointersInitializesStatements += setPointerField
		}

	}

	for idx, value := range valueOrdered {
		var setPointerField string
		_ = setPointerField

		id = generatesIdentifier("Value", idx, value.Name)
		map_Value_Identifiers[value] = id

		// Initialisation of values
	}

	res = strings.ReplaceAll(res, "{{Identifiers}}", identifiersDecl)
	res = strings.ReplaceAll(res, "{{ValueInitializers}}", initializerStatements)
	res = strings.ReplaceAll(res, "{{PointersInitializers}}", pointersInitializesStatements)

	fmt.Fprintln(file, res)
}

// unique identifier per struct
func generatesIdentifier(gongStructName string, idx int, instanceName string) (identifier string) {

	identifier = instanceName
	// Make a Regex to say we only want letters and numbers
	reg, err := regexp.Compile("[^a-zA-Z0-9]+")
	if err != nil {
		log.Fatal(err)
	}
	processedString := reg.ReplaceAllString(instanceName, "_")

	identifier = fmt.Sprintf("__%s__%06d_%s", gongStructName, idx, processedString)

	return
}

// insertion point of functions that provide maps for reverse associations

// generate function for reverse association maps of Bar
func (stageStruct *StageStruct) CreateReverseMap_Bar_X() (res map[*Key][]*Bar) {
	res = make(map[*Key][]*Bar)

	for bar := range stageStruct.Bars {
		if bar.X != nil {
			key_ := bar.X
			var bars []*Bar
			_, ok := res[key_]
			if ok {
				bars = res[key_]
			} else {
				bars = make([]*Bar, 0)
			}
			bars = append(bars, bar)
			res[key_] = bars
		}
	}

	return
}
func (stageStruct *StageStruct) CreateReverseMap_Bar_Y() (res map[*Key][]*Bar) {
	res = make(map[*Key][]*Bar)

	for bar := range stageStruct.Bars {
		if bar.Y != nil {
			key_ := bar.Y
			var bars []*Bar
			_, ok := res[key_]
			if ok {
				bars = res[key_]
			} else {
				bars = make([]*Bar, 0)
			}
			bars = append(bars, bar)
			res[key_] = bars
		}
	}

	return
}
func (stageStruct *StageStruct) CreateReverseMap_Bar_Set() (res map[*Serie]*Bar) {
	res = make(map[*Serie]*Bar)

	for bar := range stageStruct.Bars {
		for _, serie_ := range bar.Set {
			res[serie_] = bar
		}
	}

	return
}


// generate function for reverse association maps of Key

// generate function for reverse association maps of Pie
func (stageStruct *StageStruct) CreateReverseMap_Pie_X() (res map[*Key][]*Pie) {
	res = make(map[*Key][]*Pie)

	for pie := range stageStruct.Pies {
		if pie.X != nil {
			key_ := pie.X
			var pies []*Pie
			_, ok := res[key_]
			if ok {
				pies = res[key_]
			} else {
				pies = make([]*Pie, 0)
			}
			pies = append(pies, pie)
			res[key_] = pies
		}
	}

	return
}
func (stageStruct *StageStruct) CreateReverseMap_Pie_Y() (res map[*Key][]*Pie) {
	res = make(map[*Key][]*Pie)

	for pie := range stageStruct.Pies {
		if pie.Y != nil {
			key_ := pie.Y
			var pies []*Pie
			_, ok := res[key_]
			if ok {
				pies = res[key_]
			} else {
				pies = make([]*Pie, 0)
			}
			pies = append(pies, pie)
			res[key_] = pies
		}
	}

	return
}
func (stageStruct *StageStruct) CreateReverseMap_Pie_Set() (res map[*Serie]*Pie) {
	res = make(map[*Serie]*Pie)

	for pie := range stageStruct.Pies {
		for _, serie_ := range pie.Set {
			res[serie_] = pie
		}
	}

	return
}


// generate function for reverse association maps of Serie
func (stageStruct *StageStruct) CreateReverseMap_Serie_Key() (res map[*Key][]*Serie) {
	res = make(map[*Key][]*Serie)

	for serie := range stageStruct.Series {
		if serie.Key != nil {
			key_ := serie.Key
			var series []*Serie
			_, ok := res[key_]
			if ok {
				series = res[key_]
			} else {
				series = make([]*Serie, 0)
			}
			series = append(series, serie)
			res[key_] = series
		}
	}

	return
}
func (stageStruct *StageStruct) CreateReverseMap_Serie_Values() (res map[*Value]*Serie) {
	res = make(map[*Value]*Serie)

	for serie := range stageStruct.Series {
		for _, value_ := range serie.Values {
			res[value_] = serie
		}
	}

	return
}


// generate function for reverse association maps of Value

// Gongstruct is the type parameter for generated generic function that allows
// - access to staged instances
// - navigation between staged instances by going backward association links between gongstruct
// - full refactoring of Gongstruct identifiers / fields
type Gongstruct interface {
	// insertion point for generic types
	Bar | Key | Pie | Serie | Value
}

// Gongstruct is the type parameter for generated generic function that allows
// - access to staged instances
// - navigation between staged instances by going backward association links between gongstruct
// - full refactoring of Gongstruct identifiers / fields
type PointerToGongstruct interface {
	// insertion point for generic types
	*Bar | *Key | *Pie | *Serie | *Value
	GetName() string
}

type GongstructSet interface {
	map[any]any |
		// insertion point for generic types
		map[*Bar]any |
		map[*Key]any |
		map[*Pie]any |
		map[*Serie]any |
		map[*Value]any |
		map[*any]any // because go does not support an extra "|" at the end of type specifications
}

type GongstructMapString interface {
	map[any]any |
		// insertion point for generic types
		map[string]*Bar |
		map[string]*Key |
		map[string]*Pie |
		map[string]*Serie |
		map[string]*Value |
		map[*any]any // because go does not support an extra "|" at the end of type specifications
}

// GongGetSet returns the set staged GongstructType instances
// it is usefull because it allows refactoring of gong struct identifier
func GongGetSet[Type GongstructSet]() *Type {
	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get functions
	case map[*Bar]any:
		return any(&Stage.Bars).(*Type)
	case map[*Key]any:
		return any(&Stage.Keys).(*Type)
	case map[*Pie]any:
		return any(&Stage.Pies).(*Type)
	case map[*Serie]any:
		return any(&Stage.Series).(*Type)
	case map[*Value]any:
		return any(&Stage.Values).(*Type)
	default:
		return nil
	}
}

// GongGetMap returns the map of staged GongstructType instances
// it is usefull because it allows refactoring of gong struct identifier
func GongGetMap[Type GongstructMapString]() *Type {
	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get functions
	case map[string]*Bar:
		return any(&Stage.Bars_mapString).(*Type)
	case map[string]*Key:
		return any(&Stage.Keys_mapString).(*Type)
	case map[string]*Pie:
		return any(&Stage.Pies_mapString).(*Type)
	case map[string]*Serie:
		return any(&Stage.Series_mapString).(*Type)
	case map[string]*Value:
		return any(&Stage.Values_mapString).(*Type)
	default:
		return nil
	}
}

// GetGongstructInstancesSet returns the set staged GongstructType instances
// it is usefull because it allows refactoring of gongstruct identifier
func GetGongstructInstancesSet[Type Gongstruct]() *map[*Type]any {
	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get functions
	case Bar:
		return any(&Stage.Bars).(*map[*Type]any)
	case Key:
		return any(&Stage.Keys).(*map[*Type]any)
	case Pie:
		return any(&Stage.Pies).(*map[*Type]any)
	case Serie:
		return any(&Stage.Series).(*map[*Type]any)
	case Value:
		return any(&Stage.Values).(*map[*Type]any)
	default:
		return nil
	}
}

// GetGongstructInstancesMap returns the map of staged GongstructType instances
// it is usefull because it allows refactoring of gong struct identifier
func GetGongstructInstancesMap[Type Gongstruct]() *map[string]*Type {
	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get functions
	case Bar:
		return any(&Stage.Bars_mapString).(*map[string]*Type)
	case Key:
		return any(&Stage.Keys_mapString).(*map[string]*Type)
	case Pie:
		return any(&Stage.Pies_mapString).(*map[string]*Type)
	case Serie:
		return any(&Stage.Series_mapString).(*map[string]*Type)
	case Value:
		return any(&Stage.Values_mapString).(*map[string]*Type)
	default:
		return nil
	}
}

// GetAssociationName is a generic function that returns an instance of Type
// where each association is filled with an instance whose name is the name of the association
//
// This function can be handy for generating navigation function that are refactorable
func GetAssociationName[Type Gongstruct]() *Type {
	var ret Type

	switch any(ret).(type) {
	// insertion point for instance with special fields
	case Bar:
		return any(&Bar{
			// Initialisation of associations
			// field is initialized with an instance of Key with the name of the field
			X: &Key{Name: "X"},
			// field is initialized with an instance of Key with the name of the field
			Y: &Key{Name: "Y"},
			// field is initialized with an instance of Serie with the name of the field
			Set: []*Serie{{Name: "Set"}},
		}).(*Type)
	case Key:
		return any(&Key{
			// Initialisation of associations
		}).(*Type)
	case Pie:
		return any(&Pie{
			// Initialisation of associations
			// field is initialized with an instance of Key with the name of the field
			X: &Key{Name: "X"},
			// field is initialized with an instance of Key with the name of the field
			Y: &Key{Name: "Y"},
			// field is initialized with an instance of Serie with the name of the field
			Set: []*Serie{{Name: "Set"}},
		}).(*Type)
	case Serie:
		return any(&Serie{
			// Initialisation of associations
			// field is initialized with an instance of Key with the name of the field
			Key: &Key{Name: "Key"},
			// field is initialized with an instance of Value with the name of the field
			Values: []*Value{{Name: "Values"}},
		}).(*Type)
	case Value:
		return any(&Value{
			// Initialisation of associations
		}).(*Type)
	default:
		return nil
	}
}

// GetPointerReverseMap allows backtrack navigation of any Start.Fieldname
// associations (0..1) that is a pointer from one staged Gongstruct (type Start)
// instances to another (type End)
//
// The function provides a map with keys as instances of End and values to arrays of *Start
// the map is construed by iterating over all Start instances and populationg keys with End instances
// and values with slice of Start instances
func GetPointerReverseMap[Start, End Gongstruct](fieldname string) map[*End][]*Start {
	var ret Start

	switch any(ret).(type) {
	// insertion point of functions that provide maps for reverse associations
	// reverse maps of direct associations of Bar
	case Bar:
		switch fieldname {
		// insertion point for per direct association field
		case "X":
			res := make(map[*Key][]*Bar)
			for bar := range Stage.Bars {
				if bar.X != nil {
					key_ := bar.X
					var bars []*Bar
					_, ok := res[key_]
					if ok {
						bars = res[key_]
					} else {
						bars = make([]*Bar, 0)
					}
					bars = append(bars, bar)
					res[key_] = bars
				}
			}
			return any(res).(map[*End][]*Start)
		case "Y":
			res := make(map[*Key][]*Bar)
			for bar := range Stage.Bars {
				if bar.Y != nil {
					key_ := bar.Y
					var bars []*Bar
					_, ok := res[key_]
					if ok {
						bars = res[key_]
					} else {
						bars = make([]*Bar, 0)
					}
					bars = append(bars, bar)
					res[key_] = bars
				}
			}
			return any(res).(map[*End][]*Start)
		}
	// reverse maps of direct associations of Key
	case Key:
		switch fieldname {
		// insertion point for per direct association field
		}
	// reverse maps of direct associations of Pie
	case Pie:
		switch fieldname {
		// insertion point for per direct association field
		case "X":
			res := make(map[*Key][]*Pie)
			for pie := range Stage.Pies {
				if pie.X != nil {
					key_ := pie.X
					var pies []*Pie
					_, ok := res[key_]
					if ok {
						pies = res[key_]
					} else {
						pies = make([]*Pie, 0)
					}
					pies = append(pies, pie)
					res[key_] = pies
				}
			}
			return any(res).(map[*End][]*Start)
		case "Y":
			res := make(map[*Key][]*Pie)
			for pie := range Stage.Pies {
				if pie.Y != nil {
					key_ := pie.Y
					var pies []*Pie
					_, ok := res[key_]
					if ok {
						pies = res[key_]
					} else {
						pies = make([]*Pie, 0)
					}
					pies = append(pies, pie)
					res[key_] = pies
				}
			}
			return any(res).(map[*End][]*Start)
		}
	// reverse maps of direct associations of Serie
	case Serie:
		switch fieldname {
		// insertion point for per direct association field
		case "Key":
			res := make(map[*Key][]*Serie)
			for serie := range Stage.Series {
				if serie.Key != nil {
					key_ := serie.Key
					var series []*Serie
					_, ok := res[key_]
					if ok {
						series = res[key_]
					} else {
						series = make([]*Serie, 0)
					}
					series = append(series, serie)
					res[key_] = series
				}
			}
			return any(res).(map[*End][]*Start)
		}
	// reverse maps of direct associations of Value
	case Value:
		switch fieldname {
		// insertion point for per direct association field
		}
	}
	return nil
}

// GetSliceOfPointersReverseMap allows backtrack navigation of any Start.Fieldname
// associations (0..N) between one staged Gongstruct instances and many others
//
// The function provides a map with keys as instances of End and values to *Start instances
// the map is construed by iterating over all Start instances and populating keys with End instances
// and values with the Start instances
func GetSliceOfPointersReverseMap[Start, End Gongstruct](fieldname string) map[*End]*Start {
	var ret Start

	switch any(ret).(type) {
	// insertion point of functions that provide maps for reverse associations
	// reverse maps of direct associations of Bar
	case Bar:
		switch fieldname {
		// insertion point for per direct association field
		case "Set":
			res := make(map[*Serie]*Bar)
			for bar := range Stage.Bars {
				for _, serie_ := range bar.Set {
					res[serie_] = bar
				}
			}
			return any(res).(map[*End]*Start)
		}
	// reverse maps of direct associations of Key
	case Key:
		switch fieldname {
		// insertion point for per direct association field
		}
	// reverse maps of direct associations of Pie
	case Pie:
		switch fieldname {
		// insertion point for per direct association field
		case "Set":
			res := make(map[*Serie]*Pie)
			for pie := range Stage.Pies {
				for _, serie_ := range pie.Set {
					res[serie_] = pie
				}
			}
			return any(res).(map[*End]*Start)
		}
	// reverse maps of direct associations of Serie
	case Serie:
		switch fieldname {
		// insertion point for per direct association field
		case "Values":
			res := make(map[*Value]*Serie)
			for serie := range Stage.Series {
				for _, value_ := range serie.Values {
					res[value_] = serie
				}
			}
			return any(res).(map[*End]*Start)
		}
	// reverse maps of direct associations of Value
	case Value:
		switch fieldname {
		// insertion point for per direct association field
		}
	}
	return nil
}

// GetGongstructName returns the name of the Gongstruct
// this can be usefull if one want program robust to refactoring
func GetGongstructName[Type Gongstruct]() (res string) {

	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get gongstruct name
	case Bar:
		res = "Bar"
	case Key:
		res = "Key"
	case Pie:
		res = "Pie"
	case Serie:
		res = "Serie"
	case Value:
		res = "Value"
	}
	return res
}

// GetFields return the array of the fields
func GetFields[Type Gongstruct]() (res []string) {

	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get gongstruct name
	case Bar:
		res = []string{"Name", "X", "Y", "Set", "Width", "Heigth", "Margin"}
	case Key:
		res = []string{"Name"}
	case Pie:
		res = []string{"Name", "X", "Y", "Set", "Width", "Heigth", "Margin"}
	case Serie:
		res = []string{"Name", "Key", "Values"}
	case Value:
		res = []string{"Name"}
	}
	return
}

func GetFieldStringValue[Type Gongstruct](instance Type, fieldName string) (res string) {
	var ret Type

	switch any(ret).(type) {
	// insertion point for generic get gongstruct field value
	case Bar:
		switch fieldName {
		// string value of fields
		case "Name":
			res = any(instance).(Bar).Name
		case "X":
			if any(instance).(Bar).X != nil {
				res = any(instance).(Bar).X.Name
			}
		case "Y":
			if any(instance).(Bar).Y != nil {
				res = any(instance).(Bar).Y.Name
			}
		case "Set":
			for idx, __instance__ := range any(instance).(Bar).Set {
				if idx > 0 {
					res += "\n"
				}
				res += __instance__.Name
			}
		case "Width":
			res = fmt.Sprintf("%f", any(instance).(Bar).Width)
		case "Heigth":
			res = fmt.Sprintf("%f", any(instance).(Bar).Heigth)
		case "Margin":
			res = fmt.Sprintf("%f", any(instance).(Bar).Margin)
		}
	case Key:
		switch fieldName {
		// string value of fields
		case "Name":
			res = any(instance).(Key).Name
		}
	case Pie:
		switch fieldName {
		// string value of fields
		case "Name":
			res = any(instance).(Pie).Name
		case "X":
			if any(instance).(Pie).X != nil {
				res = any(instance).(Pie).X.Name
			}
		case "Y":
			if any(instance).(Pie).Y != nil {
				res = any(instance).(Pie).Y.Name
			}
		case "Set":
			for idx, __instance__ := range any(instance).(Pie).Set {
				if idx > 0 {
					res += "\n"
				}
				res += __instance__.Name
			}
		case "Width":
			res = fmt.Sprintf("%f", any(instance).(Pie).Width)
		case "Heigth":
			res = fmt.Sprintf("%f", any(instance).(Pie).Heigth)
		case "Margin":
			res = fmt.Sprintf("%f", any(instance).(Pie).Margin)
		}
	case Serie:
		switch fieldName {
		// string value of fields
		case "Name":
			res = any(instance).(Serie).Name
		case "Key":
			if any(instance).(Serie).Key != nil {
				res = any(instance).(Serie).Key.Name
			}
		case "Values":
			for idx, __instance__ := range any(instance).(Serie).Values {
				if idx > 0 {
					res += "\n"
				}
				res += __instance__.Name
			}
		}
	case Value:
		switch fieldName {
		// string value of fields
		case "Name":
			res = any(instance).(Value).Name
		}
	}
	return
}

// insertion point of enum utility functions
// Last line of the template
