// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { SerieDB } from '../serie-db'
import { SerieService } from '../serie.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-seriestable',
  templateUrl: './series-table.component.html',
  styleUrls: ['./series-table.component.css'],
})
export class SeriesTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of Serie instances
  selection: SelectionModel<SerieDB> = new (SelectionModel)
  initialSelection = new Array<SerieDB>()

  // the data source for the table
  series: SerieDB[] = []
  matTableDataSource: MatTableDataSource<SerieDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.series
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (serieDB: SerieDB, property: string) => {
      switch (property) {
        case 'ID':
          return serieDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return serieDB.Name;

        case 'Key':
          return (serieDB.Key ? serieDB.Key.Name : '');

        case 'Bar_Set':
          if (this.frontRepo.Bars.get(serieDB.Bar_SetDBID.Int64) != undefined) {
            return this.frontRepo.Bars.get(serieDB.Bar_SetDBID.Int64)!.Name
          } else {
            return ""
          }

        case 'Pie_Set':
          if (this.frontRepo.Pies.get(serieDB.Pie_SetDBID.Int64) != undefined) {
            return this.frontRepo.Pies.get(serieDB.Pie_SetDBID.Int64)!.Name
          } else {
            return ""
          }

        case 'Scatter_Set':
          if (this.frontRepo.Scatters.get(serieDB.Scatter_SetDBID.Int64) != undefined) {
            return this.frontRepo.Scatters.get(serieDB.Scatter_SetDBID.Int64)!.Name
          } else {
            return ""
          }

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (serieDB: SerieDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the serieDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += serieDB.Name.toLowerCase()
      if (serieDB.Key) {
        mergedContent += serieDB.Key.Name.toLowerCase()
      }
      if (serieDB.Bar_SetDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Bars.get(serieDB.Bar_SetDBID.Int64)!.Name.toLowerCase()
      }

      if (serieDB.Pie_SetDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Pies.get(serieDB.Pie_SetDBID.Int64)!.Name.toLowerCase()
      }

      if (serieDB.Scatter_SetDBID.Int64 != 0) {
        mergedContent += this.frontRepo.Scatters.get(serieDB.Scatter_SetDBID.Int64)!.Name.toLowerCase()
      }


      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private serieService: SerieService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of serie instances
    public dialogRef: MatDialogRef<SeriesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.serieService.SerieServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getSeries()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "Key",
        "Bar_Set",
        "Pie_Set",
        "Scatter_Set",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "Key",
        "Bar_Set",
        "Pie_Set",
        "Scatter_Set",
      ]
      this.selection = new SelectionModel<SerieDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getSeries()

    this.matTableDataSource = new MatTableDataSource(this.series)
  }

  getSeries(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.series = this.frontRepo.Series_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let serie of this.series) {
            let ID = this.dialogData.ID
            let revPointer = serie[this.dialogData.ReversePointer as keyof SerieDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(serie)
            }
            this.selection = new SelectionModel<SerieDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, SerieDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to SerieDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as SerieDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let serie = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as SerieDB
              this.initialSelection.push(serie)
            }
          }

          this.selection = new SelectionModel<SerieDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.series
      }
    )
  }

  // newSerie initiate a new serie
  // create a new Serie objet
  newSerie() {
  }

  deleteSerie(serieID: number, serie: SerieDB) {
    // list of series is truncated of serie before the delete
    this.series = this.series.filter(h => h !== serie);

    this.serieService.deleteSerie(serieID, this.GONG__StackPath).subscribe(
      serie => {
        this.serieService.SerieServiceChanged.next("delete")
      }
    );
  }

  editSerie(serieID: number, serie: SerieDB) {

  }

  // display serie in router
  displaySerieInRouter(serieID: number) {
    this.router.navigate(["gongd3_go-" + "serie-display", serieID])
  }

  // set editor outlet
  setEditorRouterOutlet(serieID: number) {
    this.router.navigate([{
      outlets: {
        gongd3_go_editor: ["gongd3_go-" + "serie-detail", serieID, this.GONG__StackPath]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.series.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.series.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<SerieDB>()

      // reset all initial selection of serie that belong to serie
      for (let serie of this.initialSelection) {
        let index = serie[this.dialogData.ReversePointer as keyof SerieDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(serie)

      }

      // from selection, set serie that belong to serie
      for (let serie of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = serie[this.dialogData.ReversePointer as keyof SerieDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(serie)
      }


      // update all serie (only update selection & initial selection)
      for (let serie of toUpdate) {
        this.serieService.updateSerie(serie, this.GONG__StackPath)
          .subscribe(serie => {
            this.serieService.SerieServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, SerieDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedSerie = new Set<number>()
      for (let serie of this.initialSelection) {
        if (this.selection.selected.includes(serie)) {
          // console.log("serie " + serie.Name + " is still selected")
        } else {
          console.log("serie " + serie.Name + " has been unselected")
          unselectedSerie.add(serie.ID)
          console.log("is unselected " + unselectedSerie.has(serie.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let serie = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as SerieDB
      if (unselectedSerie.has(serie.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<SerieDB>) = new Array<SerieDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          serie => {
            if (!this.initialSelection.includes(serie)) {
              // console.log("serie " + serie.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + serie.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = serie.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = serie.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("serie " + serie.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<SerieDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
