// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"gongd3/go/models"
	"gongd3/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __Pie__dummysDeclaration__ models.Pie
var __Pie_time__dummyDeclaration time.Duration

// An PieID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getPie updatePie deletePie
type PieID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// PieInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postPie updatePie
type PieInput struct {
	// The Pie to submit or modify
	// in: body
	Pie *orm.PieAPI
}

// GetPies
//
// swagger:route GET /pies pies getPies
//
// # Get all pies
//
// Responses:
// default: genericError
//
//	200: pieDBResponse
func GetPies(c *gin.Context) {
	db := orm.BackRepo.BackRepoPie.GetDB()

	// source slice
	var pieDBs []orm.PieDB

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GONG__StackPath", stackParam)
		}
	}

	query := db.Find(&pieDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	pieAPIs := make([]orm.PieAPI, 0)

	// for each pie, update fields from the database nullable fields
	for idx := range pieDBs {
		pieDB := &pieDBs[idx]
		_ = pieDB
		var pieAPI orm.PieAPI

		// insertion point for updating fields
		pieAPI.ID = pieDB.ID
		pieDB.CopyBasicFieldsToPie(&pieAPI.Pie)
		pieAPI.PiePointersEnconding = pieDB.PiePointersEnconding
		pieAPIs = append(pieAPIs, pieAPI)
	}

	c.JSON(http.StatusOK, pieAPIs)
}

// PostPie
//
// swagger:route POST /pies pies postPie
//
// Creates a pie
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostPie(c *gin.Context) {

	// Validate input
	var input orm.PieAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create pie
	pieDB := orm.PieDB{}
	pieDB.PiePointersEnconding = input.PiePointersEnconding
	pieDB.CopyBasicFieldsFromPie(&input.Pie)

	db := orm.BackRepo.BackRepoPie.GetDB()
	query := db.Create(&pieDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoPie.CheckoutPhaseOneInstance(&pieDB)
	pie := (*orm.BackRepo.BackRepoPie.Map_PieDBID_PiePtr)[pieDB.ID]

	if pie != nil {
		models.AfterCreateFromFront(&models.Stage, pie)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, pieDB)
}

// GetPie
//
// swagger:route GET /pies/{ID} pies getPie
//
// Gets the details for a pie.
//
// Responses:
// default: genericError
//
//	200: pieDBResponse
func GetPie(c *gin.Context) {

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["stack"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GET params", stackParam)
		}
	}

	db := orm.BackRepo.BackRepoPie.GetDB()

	// Get pieDB in DB
	var pieDB orm.PieDB
	if err := db.First(&pieDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var pieAPI orm.PieAPI
	pieAPI.ID = pieDB.ID
	pieAPI.PiePointersEnconding = pieDB.PiePointersEnconding
	pieDB.CopyBasicFieldsToPie(&pieAPI.Pie)

	c.JSON(http.StatusOK, pieAPI)
}

// UpdatePie
//
// swagger:route PATCH /pies/{ID} pies updatePie
//
// # Update a pie
//
// Responses:
// default: genericError
//
//	200: pieDBResponse
func UpdatePie(c *gin.Context) {

	// Validate input
	var input orm.PieAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db := orm.BackRepo.BackRepoPie.GetDB()

	// Get model if exist
	var pieDB orm.PieDB

	// fetch the pie
	query := db.First(&pieDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	pieDB.CopyBasicFieldsFromPie(&input.Pie)
	pieDB.PiePointersEnconding = input.PiePointersEnconding

	query = db.Model(&pieDB).Updates(pieDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	pieNew := new(models.Pie)
	pieDB.CopyBasicFieldsToPie(pieNew)

	// get stage instance from DB instance, and call callback function
	pieOld := (*orm.BackRepo.BackRepoPie.Map_PieDBID_PiePtr)[pieDB.ID]
	if pieOld != nil {
		models.AfterUpdateFromFront(&models.Stage, pieOld, pieNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the pieDB
	c.JSON(http.StatusOK, pieDB)
}

// DeletePie
//
// swagger:route DELETE /pies/{ID} pies deletePie
//
// # Delete a pie
//
// default: genericError
//
//	200: pieDBResponse
func DeletePie(c *gin.Context) {
	db := orm.BackRepo.BackRepoPie.GetDB()

	// Get model if exist
	var pieDB orm.PieDB
	if err := db.First(&pieDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&pieDB)

	// get an instance (not staged) from DB instance, and call callback function
	pieDeleted := new(models.Pie)
	pieDB.CopyBasicFieldsToPie(pieDeleted)

	// get stage instance from DB instance, and call callback function
	pieStaged := (*orm.BackRepo.BackRepoPie.Map_PieDBID_PiePtr)[pieDB.ID]
	if pieStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, pieStaged, pieDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
