// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"gongd3/go/models"
	"gongd3/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __Value__dummysDeclaration__ models.Value
var __Value_time__dummyDeclaration time.Duration

// An ValueID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getValue updateValue deleteValue
type ValueID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// ValueInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postValue updateValue
type ValueInput struct {
	// The Value to submit or modify
	// in: body
	Value *orm.ValueAPI
}

// GetValues
//
// swagger:route GET /values values getValues
//
// # Get all values
//
// Responses:
// default: genericError
//
//	200: valueDBResponse
func GetValues(c *gin.Context) {
	db := orm.BackRepo.BackRepoValue.GetDB()

	// source slice
	var valueDBs []orm.ValueDB

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GONG__StackPath", stackParam)
		}
	}

	query := db.Find(&valueDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	valueAPIs := make([]orm.ValueAPI, 0)

	// for each value, update fields from the database nullable fields
	for idx := range valueDBs {
		valueDB := &valueDBs[idx]
		_ = valueDB
		var valueAPI orm.ValueAPI

		// insertion point for updating fields
		valueAPI.ID = valueDB.ID
		valueDB.CopyBasicFieldsToValue(&valueAPI.Value)
		valueAPI.ValuePointersEnconding = valueDB.ValuePointersEnconding
		valueAPIs = append(valueAPIs, valueAPI)
	}

	c.JSON(http.StatusOK, valueAPIs)
}

// PostValue
//
// swagger:route POST /values values postValue
//
// Creates a value
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostValue(c *gin.Context) {

	// Validate input
	var input orm.ValueAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create value
	valueDB := orm.ValueDB{}
	valueDB.ValuePointersEnconding = input.ValuePointersEnconding
	valueDB.CopyBasicFieldsFromValue(&input.Value)

	db := orm.BackRepo.BackRepoValue.GetDB()
	query := db.Create(&valueDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoValue.CheckoutPhaseOneInstance(&valueDB)
	value := (*orm.BackRepo.BackRepoValue.Map_ValueDBID_ValuePtr)[valueDB.ID]

	if value != nil {
		models.AfterCreateFromFront(&models.Stage, value)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, valueDB)
}

// GetValue
//
// swagger:route GET /values/{ID} values getValue
//
// Gets the details for a value.
//
// Responses:
// default: genericError
//
//	200: valueDBResponse
func GetValue(c *gin.Context) {

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["stack"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GET params", stackParam)
		}
	}

	db := orm.BackRepo.BackRepoValue.GetDB()

	// Get valueDB in DB
	var valueDB orm.ValueDB
	if err := db.First(&valueDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var valueAPI orm.ValueAPI
	valueAPI.ID = valueDB.ID
	valueAPI.ValuePointersEnconding = valueDB.ValuePointersEnconding
	valueDB.CopyBasicFieldsToValue(&valueAPI.Value)

	c.JSON(http.StatusOK, valueAPI)
}

// UpdateValue
//
// swagger:route PATCH /values/{ID} values updateValue
//
// # Update a value
//
// Responses:
// default: genericError
//
//	200: valueDBResponse
func UpdateValue(c *gin.Context) {

	// Validate input
	var input orm.ValueAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db := orm.BackRepo.BackRepoValue.GetDB()

	// Get model if exist
	var valueDB orm.ValueDB

	// fetch the value
	query := db.First(&valueDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	valueDB.CopyBasicFieldsFromValue(&input.Value)
	valueDB.ValuePointersEnconding = input.ValuePointersEnconding

	query = db.Model(&valueDB).Updates(valueDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	valueNew := new(models.Value)
	valueDB.CopyBasicFieldsToValue(valueNew)

	// get stage instance from DB instance, and call callback function
	valueOld := (*orm.BackRepo.BackRepoValue.Map_ValueDBID_ValuePtr)[valueDB.ID]
	if valueOld != nil {
		models.AfterUpdateFromFront(&models.Stage, valueOld, valueNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the valueDB
	c.JSON(http.StatusOK, valueDB)
}

// DeleteValue
//
// swagger:route DELETE /values/{ID} values deleteValue
//
// # Delete a value
//
// default: genericError
//
//	200: valueDBResponse
func DeleteValue(c *gin.Context) {
	db := orm.BackRepo.BackRepoValue.GetDB()

	// Get model if exist
	var valueDB orm.ValueDB
	if err := db.First(&valueDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&valueDB)

	// get an instance (not staged) from DB instance, and call callback function
	valueDeleted := new(models.Value)
	valueDB.CopyBasicFieldsToValue(valueDeleted)

	// get stage instance from DB instance, and call callback function
	valueStaged := (*orm.BackRepo.BackRepoValue.Map_ValueDBID_ValuePtr)[valueDB.ID]
	if valueStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, valueStaged, valueDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
