// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { KeyDB } from '../key-db'
import { KeyService } from '../key.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-key-sorting',
  templateUrl: './key-sorting.component.html',
  styleUrls: ['./key-sorting.component.css']
})
export class KeySortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Key instances that are in the association
  associatedKeys = new Array<KeyDB>();

  constructor(
    private keyService: KeyService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of key instances
    public dialogRef: MatDialogRef<KeySortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getKeys()
  }

  getKeys(): void {
    this.frontRepoService.pull(this.dialogData.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let key of this.frontRepo.Keys_array) {
          let ID = this.dialogData.ID
          let revPointerID = key[this.dialogData.ReversePointer as keyof KeyDB] as unknown as NullInt64
          let revPointerID_Index = key[this.dialogData.ReversePointer + "_Index" as keyof KeyDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedKeys.push(key)
          }
        }

        // sort associated key according to order
        this.associatedKeys.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedKeys, event.previousIndex, event.currentIndex);

    // set the order of Key instances
    let index = 0

    for (let key of this.associatedKeys) {
      let revPointerID_Index = key[this.dialogData.ReversePointer + "_Index" as keyof KeyDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedKeys.forEach(
      key => {
        this.keyService.updateKey(key, this.dialogData.GONG__StackPath)
          .subscribe(key => {
            this.keyService.KeyServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer + ' done');
  }
}
