// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { HelloDB } from '../hello-db'
import { HelloService } from '../hello.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-hello-sorting',
  templateUrl: './hello-sorting.component.html',
  styleUrls: ['./hello-sorting.component.css']
})
export class HelloSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of Hello instances that are in the association
  associatedHellos = new Array<HelloDB>();

  constructor(
    private helloService: HelloService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of hello instances
    public dialogRef: MatDialogRef<HelloSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getHellos()
  }

  getHellos(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let hello of this.frontRepo.Hellos_array) {
          let ID = this.dialogData.ID
          let revPointerID = hello[this.dialogData.ReversePointer as keyof HelloDB] as unknown as NullInt64
          let revPointerID_Index = hello[this.dialogData.ReversePointer + "_Index" as keyof HelloDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedHellos.push(hello)
          }
        }

        // sort associated hello according to order
        this.associatedHellos.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedHellos, event.previousIndex, event.currentIndex);

    // set the order of Hello instances
    let index = 0

    for (let hello of this.associatedHellos) {
      let revPointerID_Index = hello[this.dialogData.ReversePointer + "_Index" as keyof HelloDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedHellos.forEach(
      hello => {
        this.helloService.updateHello(hello)
          .subscribe(hello => {
            this.helloService.HelloServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
